baseURL = "blog"
languageCode = "fa-ir"
title = "اپیوئید"
theme = "hugo-xmin"
footnotereturnlinkcontents = "↩"
disqusShortname = "az-sefr"
publishDir = "docs"

[[menu.main]]
    name = "خانه"
    url = "/"
    weight = 1

[[menu.main]]
    name = "وبلاگ"
    url = "/post"
    weight = 1

[[menu.main]]
    name = "پروژه‌ی ایکس"
    url = "/x-project"
    weight=1.5

[[menu.main]]
    name = "کتاب‌ها"
    url = "/book"
    weight=1.5

[[menu.main]]
    name = "مهاجرت به کانادا"
    url = "/canada"
    weight=2

[[menu.main]]
    name = "اشعار"
    url = "/poem"
    weight=2

[[menu.main]]
    name = "روزنوشت"
    url = "/rooznevesht"
    weight = 2

[[menu.main]]
    name = "پراکنده"
    url = "/random/"
    weight = 3

[[menu.main]]
    name = "درباره من"
    url = "/about/"
    weight = 4

[[menu.main]]
    name = "صفحه‌ی شخصی"
    url = "http://py4.ir"
    weight = 5

[[menu.main]]
    name = "اشتراک"
    url = "/index.xml"

[Params]
description = "در تلاش برای رهایی از این گرداب"
twitter = "https://twitter.com/ibtkm"
homepage = "http://py4.ir/"
author = "پویا"

